[phases.setup]
nixPkgs = ["python312", "postgresql"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -e ."
]

[start]
cmd = "uvicorn src.server:app --host 0.0.0.0 --port $PORT"
